In [1]:
import torch

In [ ]:
data = torch.rand(3,3 )
data

tensor([[0.4033, 0.5582, 0.5700],
        [0.0798, 0.3525, 0.9072],
        [0.9249, 0.1160, 0.5053]])

In [ ]:
data1 = torch.tensor([[1,2,3],[3,4, 4],[5,6, 5]])
data1


tensor([[1, 2, 3],
        [3, 4, 4],
        [5, 6, 5]])

In [ ]:
data2 = data1 + data
data2

tensor([[1.4033, 2.5582, 3.5700],
        [3.0798, 4.3525, 4.9072],
        [5.9249, 6.1160, 5.5053]])

Random arr

In [2]:
data = torch.randint(low=0, high=10, size=(3,3))
data

tensor([[7, 0, 3],
        [9, 6, 1],
        [0, 2, 6]])

Tìm max theo cột

In [4]:
a = data.argmax(axis=0)
a

tensor([1, 1, 2])

Max theo hàng

In [6]:
data

tensor([[7, 0, 3],
        [9, 6, 1],
        [0, 2, 6]])

In [5]:
b = data.argmax(axis=1)
b

tensor([0, 0, 2])

Đạo hàm

In [8]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2
z = 3 * y + 2

z.backward()
x.grad

tensor(12.)

In [13]:
import torch.nn as nn
import torch

# Tạo 1 layer linear có 4 node input và 1 output
linear = nn.Linear(4,1)

# Set giá trị có thể không cần set
linear.bias.data = torch.tensor([1.0, 2.0, 3.0, 4.0])
linear.weight.data = torch.tensor([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]])

# Hàm lỗi và tối ưu hàm lỗi
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

print(f'b - {linear.bias}')
print(f'w - {linear.weight}')

b - Parameter containing:
tensor([1., 2., 3., 4.], requires_grad=True)
w - Parameter containing:
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], requires_grad=True)
